# Use the official Bun image
FROM oven/bun:latest

# Set the working directory
WORKDIR /app

# Set Environment Variables
ENV AUTH0_AUDIENCE=$AUTH0_AUDIENCE
ENV AUTH0_DISABLED=$AUTH0_DISABLED
ENV AUTH0_ISSUER=$AUTH0_ISSUER
ENV AUTH0_JWKS_URI=$AUTH0_JWKS_URI
ENV CRON_ENABLED=$CRON_ENABLED
ENV ENABLE_REPETITION_GROUPING=$ENABLE_REPETITION_GROUPING
ENV LOCAL_TLS_CERT=$LOCAL_TLS_CERT
ENV MAX_SHITTY_POINTS_PER_DOING=$MAX_SHITTY_POINTS_PER_DOING
ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV SEED_DATABASE=$SEED_DATABASE
ENV SQLITE_PATH=$SQLITE_PATH
ENV USER_INVITATION_CODE=$USER_INVITATION_CODE
ENV VITE_AUTH0_AUDIENCE=$VITE_AUTH0_AUDIENCE
ENV VITE_AUTH0_CLIENT_ID=$VITE_AUTH0_CLIENT_ID
ENV VITE_AUTH0_DOMAIN=$VITE_AUTH0_DOMAIN
ENV VITE_DEV_BACKEND_URL=$VITE_DEV_BACKEND_URL

# Copy the backend code
COPY . .

# Install dependencies and build the project
RUN bun run inst
RUN bun run build

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["bun", "run", "start"]
