# Use the official Bun image
FROM oven/bun:1.2.0

# Set the working directory
WORKDIR /app

# Define build arguments
ARG AUTH0_AUDIENCE
ARG AUTH0_DISABLED
ARG AUTH0_ISSUER
ARG AUTH0_JWKS_URI
ARG CRON_ENABLED
ARG ENABLE_REPETITION_GROUPING
ARG LOCAL_TLS_CERT
ARG MAX_SHITTY_POINTS_PER_DOING
ARG NODE_ENV
ARG PORT
ARG SEED_DATABASE
ARG SQLITE_PATH
ARG VITE_AUTH0_AUDIENCE
ARG VITE_AUTH0_CLIENT_ID
ARG VITE_AUTH0_DOMAIN
ARG VITE_DEV_BACKEND_URL

# Set environment variables
ENV AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
ENV AUTH0_DISABLED=${AUTH0_DISABLED}
ENV AUTH0_ISSUER=${AUTH0_ISSUER}
ENV AUTH0_JWKS_URI=${AUTH0_JWKS_URI}
ENV CRON_ENABLED=${CRON_ENABLED}
ENV ENABLE_REPETITION_GROUPING=${ENABLE_REPETITION_GROUPING}
ENV LOCAL_TLS_CERT=${LOCAL_TLS_CERT}
ENV MAX_SHITTY_POINTS_PER_DOING=${MAX_SHITTY_POINTS_PER_DOING}
ENV NODE_ENV=${NODE_ENV}
ENV PORT=${PORT}
ENV SEED_DATABASE=${SEED_DATABASE}
ENV SQLITE_PATH=${SQLITE_PATH}
ENV VITE_AUTH0_AUDIENCE=${VITE_AUTH0_AUDIENCE}
ENV VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
ENV VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
ENV VITE_DEV_BACKEND_URL=${VITE_DEV_BACKEND_URL}

# Copy the backend code
COPY . .

# Install dependencies and build the project
RUN bun run inst
RUN bun run build

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["bun", "run", "start"]
